### ISSUE TITLE
Time to yank maybe?

### ISSUE THREAD

**Issue by andrewshadura** [dremon/mkstemp.rs#2]
Hi,

As far as I can tell, there are tempfile and tempdir which do the same thing as your crate and seem to be more popular, maybe it’d be best to yank yours to reduce the number of options to choose from?

Thanks for considering, and I hope it doesn’t come across the wrong way :slightly_smiling_face:

**Comment by ancwrd1** [comment]
I've added a deprecation note in the README file. Won't yank it from the registry.
